[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["openzeppelin-contracts=lib/openzeppelin-contracts/contracts/"]
via_ir = true
fs_permissions = [{ access = "read", path = "./.env" }]

[rpc_endpoints]
arc_testnet = "https://rpc.testnet.arc.network"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
